name: Car-api
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Listing the files
        run: ls
      - name: Building the java code with Gradle
        run: ./gradlew build
        
        
