name: Car-api
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: verify the java version
        run: java -version 
      - name: verify the Gradle version
        run: gradle -version
      - name: Gradel Build
        run: gradle build
      - run: ls /build/libs
      - name: upload the jar file
        uses: actions/upload arctifact@v2
        with: 
          path: ./build/libs/
          retention-days: 5
          
      
        
        
