name: Java Workflow

on:
  push:
    branches:
      - main

jobs:

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: build the file
  #       run: gradle build
        
  #     - run: ls ./build/libs

  #     - name: Upload the file
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: CarsAPIJar
  #         path: ./build/libs/
  #         retention-days: 5

  # testing:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Download the Artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: CarsAPIJar

  #     - name: Run the Jar file in the Background and test
  #       run: |
  #         java -jar cars-api.jar &
  #         sleep 30
  #         curl http://localhost:5000/cars/1 | grep -i "Ford"


  component-analysis:
    runs-on: ubuntu-latest
    #needs: testing
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11      

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Provide Permission
        run: chmod +x gradlew

      - run: ./gradlew pmdMain pmdTest

      - uses: actions/upload-artifact@v2
        with:
          name: PMDScanOutput
          path: build/reports/pmd

  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Provide Permission
        run: chmod +x gradlew

      - run: ./gradlew test

      - uses: actions/upload-artifact@v2
        with:
          name: UnitCasesOutput
          path: build/reports/tests

      - uses: mikepenz/action-junit-report@v2
        with:
          report_paths: build/test-results/test/*.xml
